[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "h3xrecon_plugins"
version = "0.0.1"
description = "Worker Plugins for h3xrecon bug bounty reconnaissance automation"
authors = [
    { name = "h3xitsec", email = "connect@h3x.it" },
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "asyncpg==0.30.0",
    "docopt==0.6.2",
    "loguru==0.7.2",
    "nats-py==2.9.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "PyYAML==6.0.2",
    "six==1.16.0",
    "tabulate==0.9.0",
    "h3xrecon_core @ git+https://github.com/h3xitsec/h3xrecon-core.git@v0.0.1"
]

[tool.hatch.metadata]
allow-direct-references = true
