name: Build and Release Worker Plugins

on:
  workflow_dispatch:
  workflow_call:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - develop
    # Sequence of patterns matched against refs/tags
    tags:
      - v0.*


permissions:
  packages: write
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugins repository
        uses: actions/checkout@v3
        with:
          repository: h3xitsec/h3xrecon-plugins
          path: h3xrecon-plugins
          ref: ${{ github.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - run: |
          pwd
          ls -laR
        working-directory: h3xrecon-plugins/
      
      - name: Build package
        working-directory: h3xrecon-plugins/
        run: |
          python -m build
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v0.0.1"
          files: |
            h3xrecon-plugins/dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}